name = "cactus-kafe"
compatibility_date = "2026-04-26"

assets = { directory = "." }

compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[env.production]
vars = { ENVIRONMENT = "production" }

[[routes]]
pattern = "cactuscafes.com"
custom_domain = true

[[routes]]
pattern = "www.cactuscafes.com"
custom_domain = true

[env.staging]
vars = { ENVIRONMENT = "staging" }
